services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    volumes:
      - .:/var/www/html
    networks:
      - app-network
    depends_on:
      - db
    ports:
      - "127.0.0.1:${DOCKER_WEB_APP_PORT:-4080}:80"

  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_DATABASE: crud_db
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network
    command: --default-authentication-plugin=mysql_native_password

  web_server:
    image: nginx:1.23.1-alpine
    container_name: nginx_server
    restart: unless-stopped
    tty: true
    volumes:
      - ./nginx:/etc/nginx/conf.d
    networks:
      - app-network
    depends_on:
      - app
    ports:
      - "127.0.0.1:8080:80"

  we_serve:
    image: httpd:2.4
    container_name: we_serve
    restart: unless-stopped
    tty: true
    volumes:
      - ./html:/usr/local/apache2/htdocs
    networks:
      - app-network
    depends_on:
      - db
    ports:
      - "127.0.0.1:9090:80"

networks:
  app-network:
    driver: bridge

volumes:
  db_data:
